version: '3'
services:
  my-mysql-db:
    image: mysql:8.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: demo
  my-spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - my-mysql-db
